### PR TITLE
fixing JS8 messages

### PR DESCRIPTION
**Pull request by rassware**
This fix brings JS8 messages back to life. I have tested it on my own installation with some test JS8 CQs from my station.
image

### CODE REVIEW

**Comment by rassware** [comment]
This fix brings JS8 messages back to life.

**Comment by luarvique** [comment]
I will merge it, since it looks harmless enough, but what exactly has been broken with JS8 that you are trying to fix? I am able to receive JS8 as-is, without your changes.

**Comment by rassware** [comment]
I´m sorry, you are right. I should describe my problem better.

So, my installation was built als Docker container from scratch on a Raspi 4. I didn´t use the image for Raspi.
On JS8 frequencies I couldn´t see any messages (I send my own messages ;)), so I digged into the code. In the logs was an exception that the JS8 message object has no attribute "callsign". So, I looked into the lib for JS8 from Jakob.
There was a change in the structure of the callsign data on Nov 30, 2022. Commit: https://github.com/jketterl/js8py/commit/f7e394b7892d26cbdcce5d43c0b4081a2a6a48f6

But you said, your decoding of JS8 is fine. So I looked in the lib again today and I found that the change was done on the default branch of the lib which is "develop". And I think my docker build had used this branch and not the master branch.

So, maybe there could be an issue with my fix.

**Comment by rassware** [comment]
Yes, in the docker build the develop branch form the js8py lib is used:
https://github.com/luarvique/openwebrx/blob/9b88e6130b4e710b8753603ea5d3adc7cc340e19/docker/scripts/add-owrx-tools.sh#L28

My provided fix works for docker builds. I don´t know, if there is a problem with the image release.

**Comment by luarvique** [comment]
Acknowledged. I will roll back the fix for now and inform the Docker image maintainer.

**Comment by rassware** [comment]
Yep, that is the best solution. Thanks!

**Comment by 0xAF** [comment]
#13 should revert back to stable version of js8py and fix the problem.

**Comment by 0xAF** [comment]
@rassware, can you check with the latest nightly image?
https://hub.docker.com/r/slechev/openwebrxplus-nightly

**Comment by rassware** [comment]
@0xAF, I looked into the container and the code base seems to be fine. Unfortunately, I could not do a full function test, because of hardware restrictions on my side.

**Pull request merged**
